#!/bin/bash

app_dir=s3d_app
if [ ! -d $app_dir ]; then
  echo "INFO: Preparing $app_dir"
  python3 -m venv $app_dir
  . "./$app_dir/bin/activate"
  pip install pip --upgrade
  pip install --no-cache-dir --upgrade -r ./requirements.txt
  pip install uvicorn[standard]
else
  . "./$app_dir/bin/activate"
fi

